# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geo_sentiment
                                 A QGIS plugin
 geo_sentiment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-25
        copyright            : (C) 2023 by is_department
        email                : jackmahfouz766@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load geo_sentiment class from file geo_sentiment.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_sentiment import geo_sentiment
    return geo_sentiment(iface)
